version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - MONGO_URI=mongodb+srv://bmw_user:bmw12345@cluster0.snmr7a5.mongodb.net/bmw-db?retryWrites=true&w=majority
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always
